In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from glob import glob

pd.set_option("display.max_columns", 500)
plt.style.use("seaborn-colorblind")
pal = sns.color_palette()

/var/folders/bv/l32lnnz566v9xm218mhmqy5m0000gn/T/ipykernel_66374/760691403.py:8: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use("seaborn-colorblind")

In [2]:
csv_files = glob("../raw_data/*.csv")

In [4]:
csv_files[0]

'../raw_data/Combined_Flights_2019.csv'

In [7]:
df = pd.read_csv(csv_files[0])

In [8]:
df.head()

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2019-04-01,Envoy Air,LIT,ORD,False,False,1212,1209.0,0.0,-3.0,1350.0,0.0,83.0,113.0,101.0,552.0,2019,2,4,1,1,AA,AA_CODESHARE,19805,AA,3315,MQ,20398,MQ,N253NN,3315,12992,1299206,32600,"Little Rock, AR",AR,5,Arkansas,71,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,1200-1259,10.0,1219.0,1342.0,8.0,1405,-15.0,0.0,-1.0,1400-1459,3,0
1,2019-04-02,Envoy Air,LIT,ORD,False,False,1212,1200.0,0.0,-12.0,1348.0,0.0,89.0,113.0,108.0,552.0,2019,2,4,2,2,AA,AA_CODESHARE,19805,AA,3315,MQ,20398,MQ,N242NN,3315,12992,1299206,32600,"Little Rock, AR",AR,5,Arkansas,71,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,1200-1259,10.0,1210.0,1339.0,9.0,1405,-17.0,0.0,-2.0,1400-1459,3,0
2,2019-04-03,Envoy Air,LIT,ORD,False,False,1212,1203.0,0.0,-9.0,1342.0,0.0,82.0,113.0,99.0,552.0,2019,2,4,3,3,AA,AA_CODESHARE,19805,AA,3315,MQ,20398,MQ,N247NN,3315,12992,1299206,32600,"Little Rock, AR",AR,5,Arkansas,71,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,1200-1259,11.0,1214.0,1336.0,6.0,1405,-23.0,0.0,-2.0,1400-1459,3,0
3,2019-04-04,Envoy Air,LIT,ORD,False,False,1212,1435.0,143.0,143.0,1621.0,136.0,83.0,113.0,106.0,552.0,2019,2,4,4,4,AA,AA_CODESHARE,19805,AA,3315,MQ,20398,MQ,N220NN,3315,12992,1299206,32600,"Little Rock, AR",AR,5,Arkansas,71,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,9.0,1200-1259,17.0,1452.0,1615.0,6.0,1405,136.0,1.0,9.0,1400-1459,3,0
4,2019-04-05,Envoy Air,LIT,ORD,False,False,1212,1216.0,4.0,4.0,1410.0,5.0,83.0,113.0,114.0,552.0,2019,2,4,5,5,AA,AA_CODESHARE,19805,AA,3315,MQ,20398,MQ,N255NN,3315,12992,1299206,32600,"Little Rock, AR",AR,5,Arkansas,71,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,0.0,1200-1259,18.0,1234.0,1357.0,13.0,1405,5.0,0.0,0.0,1400-1459,3,0

In [9]:
df.columns

Index(['FlightDate', 'Airline', 'Origin', 'Dest', 'Cancelled', 'Diverted',
       'CRSDepTime', 'DepTime', 'DepDelayMinutes', 'DepDelay', 'ArrTime',
       'ArrDelayMinutes', 'AirTime', 'CRSElapsedTime', 'ActualElapsedTime',
       'Distance', 'Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek',
       'Marketing_Airline_Network', 'Operated_or_Branded_Code_Share_Partners',
       'DOT_ID_Marketing_Airline', 'IATA_Code_Marketing_Airline',
       'Flight_Number_Marketing_Airline', 'Operating_Airline',
       'DOT_ID_Operating_Airline', 'IATA_Code_Operating_Airline',
       'Tail_Number', 'Flight_Number_Operating_Airline', 'OriginAirportID',
       'OriginAirportSeqID', 'OriginCityMarketID', 'OriginCityName',
       'OriginState', 'OriginStateFips', 'OriginStateName', 'OriginWac',
       'DestAirportID', 'DestAirportSeqID', 'DestCityMarketID', 'DestCityName',
       'DestState', 'DestStateFips', 'DestStateName', 'DestWac', 'DepDel15',
       'DepartureDelayGroups', 'DepTimeBlk', 'TaxiOut', 'WheelsOff',
       'WheelsOn', 'TaxiIn', 'CRSArrTime', 'ArrDelay', 'ArrDel15',
       'ArrivalDelayGroups', 'ArrTimeBlk', 'DistanceGroup',
       'DivAirportLandings'],
      dtype='object')

Features:
    "FlightDate",
    "Year', 
    'Quarter', 
    'Month', 
    'DayofMonth', 
    'DayOfWeek',
    "Airline",
    "Flight_Number_Marketing_Airline", ?
    "Origin",
    "Dest",
    "CRSDepTime",
    "OriginAirportID", # need to get list of airport ID to human readable airport name 
    "OriginCityName", ?
    "OriginStateName", ?
    "DestAirportID",
    "DestCityName", ?
    "DestStateName", ?
    "CRSArrTime",
    "Distance",
    "Flight time" # feature engineered, ? 
    
    
Targets:   
    "ArrDelayMinutes",
    "Cancelled",
    "Diverted", # make sure targets don't overlap
]

"DepDelayMinutes",

In [37]:
column_subset = ["FlightDate",
                 "Year", 
                 'Quarter', 
                 'Month', 
                 'DayofMonth', 
                 'DayOfWeek',
                 "Airline",
                 "Operating_Airline",
                 "Marketing_Airline_Network",
                 "Flight_Number_Marketing_Airline",
                 "Origin",
                 "Dest",
                 "CRSDepTime",
                 "OriginAirportID", 
                 "OriginCityName", 
                 "OriginStateName", 
                 "DestAirportID",
                 "DestCityName", 
                 "DestStateName", 
                 "CRSArrTime",
                 "Distance",
                 #"Flight time", we're going to derive this later! 
                 "ArrDelayMinutes",
                 "Cancelled",
                 "Diverted"]

In [29]:
print(csv_files)

['../raw_data/Combined_Flights_2019.csv', '../raw_data/Combined_Flights_2018.csv', '../raw_data/Combined_Flights_2022.csv', '../raw_data/Combined_Flights_2020.csv', '../raw_data/Combined_Flights_2021.csv']

In [38]:
csv_2019 = pd.read_csv('../raw_data/Combined_Flights_2019.csv')

csv_2019 = csv_2019[column_subset]

In [39]:
csv_2018 = pd.read_csv('../raw_data/Combined_Flights_2018.csv')

csv_2018 = csv_2018[column_subset]

In [40]:
csv_2020 = pd.read_csv('../raw_data/Combined_Flights_2020.csv')

csv_2020 = csv_2020[column_subset]

In [41]:
csv_2021 = pd.read_csv('../raw_data/Combined_Flights_2021.csv')

csv_2021 = csv_2021[column_subset]

In [42]:
csv_2022 = pd.read_csv('../raw_data/Combined_Flights_2022.csv')

csv_2022 = csv_2022[column_subset]

In [43]:
csv_2022.head()

,FlightDate,Year,Quarter,Month,DayofMonth,DayOfWeek,Airline,Operating_Airline,Marketing_Airline_Network,Flight_Number_Marketing_Airline,Origin,Dest,CRSDepTime,OriginAirportID,OriginCityName,OriginStateName,DestAirportID,DestCityName,DestStateName,CRSArrTime,Distance,ArrDelayMinutes,Cancelled,Diverted
0,2022-04-04,2022,2,4,4,1,"Commutair Aka Champlain Enterprises, Inc.",C5,UA,4301,GJT,DEN,1133,11921,"Grand Junction, CO",Colorado,11292,"Denver, CO",Colorado,1245,212.0,0.0,False,False
1,2022-04-04,2022,2,4,4,1,"Commutair Aka Champlain Enterprises, Inc.",C5,UA,4299,HRL,IAH,732,12206,"Harlingen/San Benito, TX",Texas,12266,"Houston, TX",Texas,849,295.0,0.0,False,False
2,2022-04-04,2022,2,4,4,1,"Commutair Aka Champlain Enterprises, Inc.",C5,UA,4298,DRO,DEN,1529,11413,"Durango, CO",Colorado,11292,"Denver, CO",Colorado,1639,251.0,0.0,False,False
3,2022-04-04,2022,2,4,4,1,"Commutair Aka Champlain Enterprises, Inc.",C5,UA,4296,IAH,GPT,1435,12266,"Houston, TX",Texas,11973,"Gulfport/Biloxi, MS",Mississippi,1605,376.0,0.0,False,False
4,2022-04-04,2022,2,4,4,1,"Commutair Aka Champlain Enterprises, Inc.",C5,UA,4295,DRO,DEN,1135,11413,"Durango, CO",Colorado,11292,"Denver, CO",Colorado,1245,251.0,6.0,False,False

In [44]:
combined = pd.concat([csv_2018,csv_2019, csv_2020, csv_2021, csv_2022], ignore_index=True)

In [48]:
combined.to_csv('../raw_data/combined_subset.csv')

In [51]:
percent_missing = combined.isnull().sum() * 100 / len(combined)
percent_missing

FlightDate                         0.000000
Year                               0.000000
Quarter                            0.000000
Month                              0.000000
DayofMonth                         0.000000
DayOfWeek                          0.000000
Airline                            0.000000
Operating_Airline                  0.000000
Marketing_Airline_Network          0.000000
Flight_Number_Marketing_Airline    0.000000
Origin                             0.000000
Dest                               0.000000
CRSDepTime                         0.000000
OriginAirportID                    0.000000
OriginCityName                     0.000000
OriginStateName                    0.000000
DestAirportID                      0.000000
DestCityName                       0.000000
DestStateName                      0.000000
CRSArrTime                         0.000000
Distance                           0.000000
ArrDelayMinutes                    2.898504
Cancelled                          0.000000
Diverted                           0.000000
dtype: float64

## Train Test Split

In [52]:
combined.head()

,FlightDate,Year,Quarter,Month,DayofMonth,DayOfWeek,Airline,Operating_Airline,Marketing_Airline_Network,Flight_Number_Marketing_Airline,Origin,Dest,CRSDepTime,OriginAirportID,OriginCityName,OriginStateName,DestAirportID,DestCityName,DestStateName,CRSArrTime,Distance,ArrDelayMinutes,Cancelled,Diverted
0,2018-01-23,2018,1,1,23,2,Endeavor Air Inc.,9E,DL,3298,ABY,ATL,1202,10146,"Albany, GA",Georgia,10397,"Atlanta, GA",Georgia,1304,145.0,0.0,False,False
1,2018-01-24,2018,1,1,24,3,Endeavor Air Inc.,9E,DL,3298,ABY,ATL,1202,10146,"Albany, GA",Georgia,10397,"Atlanta, GA",Georgia,1304,145.0,0.0,False,False
2,2018-01-25,2018,1,1,25,4,Endeavor Air Inc.,9E,DL,3298,ABY,ATL,1202,10146,"Albany, GA",Georgia,10397,"Atlanta, GA",Georgia,1304,145.0,0.0,False,False
3,2018-01-26,2018,1,1,26,5,Endeavor Air Inc.,9E,DL,3298,ABY,ATL,1202,10146,"Albany, GA",Georgia,10397,"Atlanta, GA",Georgia,1304,145.0,0.0,False,False
4,2018-01-27,2018,1,1,27,6,Endeavor Air Inc.,9E,DL,3298,ABY,ATL,1400,10146,"Albany, GA",Georgia,10397,"Atlanta, GA",Georgia,1500,145.0,0.0,False,False

In [53]:
X = combined.drop(columns = ['ArrDelayMinutes','Cancelled','Diverted'])
X.head()

,FlightDate,Year,Quarter,Month,DayofMonth,DayOfWeek,Airline,Operating_Airline,Marketing_Airline_Network,Flight_Number_Marketing_Airline,Origin,Dest,CRSDepTime,OriginAirportID,OriginCityName,OriginStateName,DestAirportID,DestCityName,DestStateName,CRSArrTime,Distance
0,2018-01-23,2018,1,1,23,2,Endeavor Air Inc.,9E,DL,3298,ABY,ATL,1202,10146,"Albany, GA",Georgia,10397,"Atlanta, GA",Georgia,1304,145.0
1,2018-01-24,2018,1,1,24,3,Endeavor Air Inc.,9E,DL,3298,ABY,ATL,1202,10146,"Albany, GA",Georgia,10397,"Atlanta, GA",Georgia,1304,145.0
2,2018-01-25,2018,1,1,25,4,Endeavor Air Inc.,9E,DL,3298,ABY,ATL,1202,10146,"Albany, GA",Georgia,10397,"Atlanta, GA",Georgia,1304,145.0
3,2018-01-26,2018,1,1,26,5,Endeavor Air Inc.,9E,DL,3298,ABY,ATL,1202,10146,"Albany, GA",Georgia,10397,"Atlanta, GA",Georgia,1304,145.0
4,2018-01-27,2018,1,1,27,6,Endeavor Air Inc.,9E,DL,3298,ABY,ATL,1400,10146,"Albany, GA",Georgia,10397,"Atlanta, GA",Georgia,1500,145.0

In [55]:
y = combined[['ArrDelayMinutes','Cancelled','Diverted']]
y.head()

   ArrDelayMinutes  Cancelled  Diverted
0              0.0      False     False
1              0.0      False     False
2              0.0      False     False
3              0.0      False     False
4              0.0      False     False

In [56]:
from sklearn.model_selection import train_test_split

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [59]:
X_train

,FlightDate,Year,Quarter,Month,DayofMonth,DayOfWeek,Airline,Operating_Airline,Marketing_Airline_Network,Flight_Number_Marketing_Airline,Origin,Dest,CRSDepTime,OriginAirportID,OriginCityName,OriginStateName,DestAirportID,DestCityName,DestStateName,CRSArrTime,Distance
4324343,2018-07-20,2018,3,7,20,5,Southwest Airlines Co.,WN,WN,2559,LAS,DAL,1200,12889,"Las Vegas, NV",Nevada,11259,"Dallas, TX",Texas,1640,1067.0
28169346,2022-01-02,2022,1,1,2,7,Spirit Air Lines,NK,NK,817,TPA,MSY,2110,15304,"Tampa, FL",Florida,13495,"New Orleans, LA",Louisiana,2148,488.0
18078508,2020-02-11,2020,1,2,11,2,Air Wisconsin Airlines Corp,ZW,UA,3798,ORD,ORF,930,13930,"Chicago, IL",Illinois,13931,"Norfolk, VA",Virginia,1245,717.0
23669089,2021-02-10,2021,1,2,10,3,United Air Lines Inc.,UA,UA,2393,TPA,IAH,700,15304,"Tampa, FL",Florida,12266,"Houston, TX",Texas,828,787.0
14530840,2020-03-12,2020,1,3,12,4,JetBlue Airways,B6,B6,754,DCA,BOS,1324,11278,"Washington, DC",Virginia,10721,"Boston, MA",Massachusetts,1455,399.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491263,2018-10-14,2018,4,10,14,7,Southwest Airlines Co.,WN,WN,3450,OAK,AUS,740,13796,"Oakland, CA",California,10423,"Austin, TX",Texas,1310,1497.0
12325960,2019-03-30,2019,1,3,30,6,Southwest Airlines Co.,WN,WN,3059,STL,DAL,1640,15016,"St. Louis, MO",Missouri,11259,"Dallas, TX",Texas,1825,546.0
6762380,2019-02-04,2019,1,2,4,1,American Airlines Inc.,AA,AA,2179,IAH,DFW,631,12266,"Houston, TX",Texas,11298,"Dallas/Fort Worth, TX",Texas,754,224.0
21463275,2021-09-08,2021,3,9,8,3,Republic Airlines,YX,UA,3544,IAD,MIA,1030,12264,"Washington, DC",Virginia,13303,"Miami, FL",Florida,1325,921.0
12710949,2019-11-10,2019,4,11,10,7,SkyWest Airlines Inc.,OO,UA,5986,PSC,LAX,1618,14252,"Pasco/Kennewick/Richland, WA",Washington,12892,"Los Angeles, CA",California,1901,851.0

In [60]:
y_train

          ArrDelayMinutes  Cancelled  Diverted
4324343               0.0      False     False
28169346              2.0      False     False
18078508              0.0      False     False
23669089              0.0      False     False
14530840              0.0      False     False
...                   ...        ...       ...
491263                0.0      False     False
12325960              3.0      False     False
6762380               0.0      False     False
21463275              0.0      False     False
12710949              0.0      False     False

[20435647 rows x 3 columns]

In [62]:
X_test.to_csv('../raw_data/x_test.csv')

In [63]:
y_test.to_csv('../raw_data/y_test.csv')

In [64]:
X_train.to_csv('../raw_data/x_train.csv')

In [65]:
y_train.to_csv('../raw_data/y_train.csv')

In [69]:
X_train[:10000].to_csv('../raw_data/initial_X_train.csv')

In [70]:
y_train[:10000].to_csv('../raw_data/initial_y_train.csv')