In [8]:
import pandas as pd
import numpy as np

In [15]:
data = pd.read_csv('../raw_data/train_subset_processed_5m.csv')
data.head()

,y_2018,y_2019,y_2020,y_2021,y_2022,dist_scaled,sin_dow,cos_dow,sin_dom,cos_dom,...,sin_qua,cos_qua,sin_dep,cos_dep,sin_arr,cos_arr,Marketing_Airline_Network,Origin,Dest,y
0,0,0,0,1,0,0.178399,-2.449294e-16,1.0,-0.571268,0.820763,...,1.0,6.123234e-17,0.220697,-0.975342,-0.714473,-0.699663,UA,ORD,SRQ,0
1,0,0,0,1,0,0.171498,-2.449294e-16,1.0,-0.571268,0.820763,...,1.0,6.123234e-17,-0.122735,-0.992439,-0.785317,-0.619094,B6,BOS,JAX,0
2,0,0,0,1,0,0.026915,-2.449294e-16,1.0,-0.571268,0.820763,...,1.0,6.123234e-17,0.918791,-0.394744,0.785317,-0.619094,AS,SEA,PSC,0
3,0,0,0,0,1,0.101104,-2.449294e-16,1.0,-0.790776,-0.612106,...,1.0,6.123234e-17,-0.490904,0.871214,-0.235990,0.971755,F9,DEN,PHX,0
4,0,0,0,0,1,0.028986,-2.449294e-16,1.0,-0.790776,-0.612106,...,1.0,6.123234e-17,0.500000,-0.866025,0.202787,-0.979223,B6,BOS,LGA,1

In [16]:
data = data.sample(frac = 1)
data

,y_2018,y_2019,y_2020,y_2021,y_2022,dist_scaled,sin_dow,cos_dow,sin_dom,cos_dom,...,sin_qua,cos_qua,sin_dep,cos_dep,sin_arr,cos_arr,Marketing_Airline_Network,Origin,Dest,y
171261,0,0,0,0,1,0.130262,9.749279e-01,-0.222521,2.012985e-01,0.979530,...,1.000000e+00,6.123234e-17,-0.872496,-4.886212e-01,-0.988494,-0.151261,AA,TYS,DFW,0
1069291,0,0,0,1,0,0.051587,4.338837e-01,-0.900969,-2.993631e-01,-0.954139,...,1.000000e+00,6.123234e-17,-1.000000,-1.836970e-16,-0.838671,0.544639,UA,ORD,CLE,0
2609279,0,0,0,0,1,0.067460,-2.449294e-16,1.000000,8.486443e-01,0.528964,...,1.224647e-16,-1.000000e+00,0.488621,-8.724960e-01,0.161604,-0.986856,NK,OAK,LAS,0
515373,0,0,0,0,1,0.107660,-2.449294e-16,1.000000,-7.247928e-01,0.688967,...,1.000000e+00,6.123234e-17,0.858065,-5.135413e-01,0.430511,-0.902585,DL,BOS,CMH,0
4810935,0,0,0,0,1,0.076777,-9.749279e-01,-0.222521,4.853020e-01,-0.874347,...,1.224647e-16,-1.000000e+00,-0.382683,-9.238795e-01,-0.743145,-0.669131,WN,MCI,DAL,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4614097,0,0,0,1,0,0.443754,-4.338837e-01,-0.900969,1.011683e-01,-0.994869,...,1.224647e-16,-1.000000e+00,0.631353,-7.754957e-01,-0.296542,-0.955020,B6,BOS,SAN,0
3803141,0,0,0,0,1,0.017771,7.818315e-01,0.623490,7.247928e-01,0.688967,...,-1.000000e+00,-1.836970e-16,0.401948,-9.156626e-01,0.143493,-0.989651,AA,PHL,DCA,0
2335419,0,0,0,0,1,0.018461,-4.338837e-01,-0.900969,-7.247928e-01,0.688967,...,1.000000e+00,6.123234e-17,-0.263873,-9.645574e-01,-0.404344,-0.914607,UA,VCT,IAH,0
3829596,0,0,0,1,0,0.285369,7.818315e-01,0.623490,-9.884683e-01,0.151428,...,1.224647e-16,-1.000000e+00,-0.902585,-4.305111e-01,-0.497731,0.867331,DL,LAX,MSY,0
1175151,0,0,0,0,1,0.070566,-4.338837e-01,-0.900969,-2.449294e-16,1.000000,...,1.000000e+00,6.123234e-17,0.645458,-7.637960e-01,0.246153,-0.969231,AA,BFL,PHX,0

In [17]:
data = data.reset_index().drop(columns = ['index'])

In [19]:
data = data.reset_index()

In [20]:
data.head()

,index,y_2018,y_2019,y_2020,y_2021,y_2022,dist_scaled,sin_dow,cos_dow,sin_dom,...,sin_qua,cos_qua,sin_dep,cos_dep,sin_arr,cos_arr,Marketing_Airline_Network,Origin,Dest,y
0,0,0,0,0,0,1,0.130262,9.749279e-01,-0.222521,0.201299,...,1.000000e+00,6.123234e-17,-0.872496,-4.886212e-01,-0.988494,-0.151261,AA,TYS,DFW,0
1,1,0,0,0,1,0,0.051587,4.338837e-01,-0.900969,-0.299363,...,1.000000e+00,6.123234e-17,-1.000000,-1.836970e-16,-0.838671,0.544639,UA,ORD,CLE,0
2,2,0,0,0,0,1,0.067460,-2.449294e-16,1.000000,0.848644,...,1.224647e-16,-1.000000e+00,0.488621,-8.724960e-01,0.161604,-0.986856,NK,OAK,LAS,0
3,3,0,0,0,0,1,0.107660,-2.449294e-16,1.000000,-0.724793,...,1.000000e+00,6.123234e-17,0.858065,-5.135413e-01,0.430511,-0.902585,DL,BOS,CMH,0
4,4,0,0,0,0,1,0.076777,-9.749279e-01,-0.222521,0.485302,...,1.224647e-16,-1.000000e+00,-0.382683,-9.238795e-01,-0.743145,-0.669131,WN,MCI,DAL,0

In [21]:
data.to_csv('../raw_data/train_subset_processed_5m_indexed.csv', index = False)